# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_data_test_bq_connector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_data_test_bq_connector.proto',
  package='data.test.bq_connector',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"event_data_test_bq_connector.proto\x12\x16\x64\x61ta.test.bq_connector\"\xc9\x01\n\x0cVTFleetEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61teTime\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12;\n\x06\x64\x65vice\x18\x06 \x01(\x0b\x32+.data.test.bq_connector.VTFleetEvent.Device\x1a*\n\x06\x44\x65vice\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\tb\x06proto3')
)




_VTFLEETEVENT_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='data.test.bq_connector.VTFleetEvent.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='data.test.bq_connector.VTFleetEvent.Device.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='database', full_name='data.test.bq_connector.VTFleetEvent.Device.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=264,
)

_VTFLEETEVENT = _descriptor.Descriptor(
  name='VTFleetEvent',
  full_name='data.test.bq_connector.VTFleetEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.test.bq_connector.VTFleetEvent.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='data.test.bq_connector.VTFleetEvent.dateTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='data.test.bq_connector.VTFleetEvent.latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='data.test.bq_connector.VTFleetEvent.longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='data.test.bq_connector.VTFleetEvent.speed', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='data.test.bq_connector.VTFleetEvent.device', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VTFLEETEVENT_DEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=264,
)

_VTFLEETEVENT_DEVICE.containing_type = _VTFLEETEVENT
_VTFLEETEVENT.fields_by_name['device'].message_type = _VTFLEETEVENT_DEVICE
DESCRIPTOR.message_types_by_name['VTFleetEvent'] = _VTFLEETEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VTFleetEvent = _reflection.GeneratedProtocolMessageType('VTFleetEvent', (_message.Message,), dict(

  Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
    DESCRIPTOR = _VTFLEETEVENT_DEVICE,
    __module__ = 'event_data_test_bq_connector_pb2'
    # @@protoc_insertion_point(class_scope:data.test.bq_connector.VTFleetEvent.Device)
    ))
  ,
  DESCRIPTOR = _VTFLEETEVENT,
  __module__ = 'event_data_test_bq_connector_pb2'
  # @@protoc_insertion_point(class_scope:data.test.bq_connector.VTFleetEvent)
  ))
_sym_db.RegisterMessage(VTFleetEvent)
_sym_db.RegisterMessage(VTFleetEvent.Device)


# @@protoc_insertion_point(module_scope)
